### PR TITLE
Added version validation on the welcome screen

### PR DESCRIPTION
**Pull request by bhavberi**
Related Backend Modification: https://github.com/IMS-IIITH/backend/commit/783fb01a773eb48083f6510f1de8e2242645795d

### CODE REVIEW

**Comment by hemanth-sunkireddy** [comment]
LGTM!

image

Here, can we add link for new version to both the pre and older versions along with the text, so users can easily find and install the new version?

**Review by hemanth-sunkireddy — APPROVED** [review]

**Comment by bhavberi** [comment]
Sure.

Not for pre, as that is fine, but for outdated versions, we can surely add a link to download the latest apk.

**Comment by bhavberi** [comment]
@hemanth-sunkireddy Once have a look now.

**Comment by hemanth-sunkireddy** [comment]
LGTM!

**Pull request merged**
