### PR TITLE
fix errors, change interfaces according to new backend changes

### PR DESCRIPTION
**Pull request by abhiramtilakiiit**
Linked to this PR: https://github.com/IMS-IIITH/backend/pull/1

Other changes include, fixing some error messages and removing some console.logs while debugging.
And I ran prettier on whatever files i touched

### CODE REVIEW

**Comment by hemanth-sunkireddy** [comment]
@abhiramtilakiiit, it looks like we are now getting the expected response from the backend. However, the details are not displaying when we apply the filter. Please check this.


Additionally, if possible, please implement a feature where selecting a year outside our range (e.g., 2021-22) displays a message such as "Please choose within your academic range" in place of "Choose Academic year and semester."
Screenshot from 2024-05-26 17-15-03

**Comment by abhiramtilakiiit** [comment]
I don't think that feature is required, It is understood by the user if the year is out of range then there will be no output. All i can do is, if the output is empty, i can display a better error message or an alert.

The problem is, currently we have to use the General Profile Details, information to fetch whether the student was there in 2021-22 or not, which requires more coupling and sending information around here and there which is too much

**Comment by bhavberi** [comment]
> I don't think that feature is required, It is understood by the user if the year is out of range then there will be no output. All i can do is, if the output is empty, i can display a better error message or an alert.
> 
> The problem is, currently we have to use the General Profile Details, information to fetch whether the student was there in 2021-22 or not, which requires more coupling and sending information around here and there which is too much

Yeah, I think this is fine. In case someone selects out of his/her academic years, you can keep it empty. 
(Although checking when someone joined shouldn't be too difficult imo - from Roll Number)

**Comment by hemanth-sunkireddy** [comment]
@abhiramtilakiiit, now the transcript is visible in the app. But the CG and SG are empty in transcript. It may be the issue with the frontend logic, Please check it once.
sg_cg

**Comment by hemanth-sunkireddy** [comment]
#26 solved

**Pull request closed without merging**
